config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  devise_scope :user do
    put "confirmation", to: "users/confirmations#show", as: :back_confirmation
  end

  root to: "boards#index"
  resources :users
  resources :boards do
    get "join" => "board#join"
    resources :favorites, only: [:create, :destroy]
    resources :lists do
      resources :cards
    end
  end
  resources :groups do
    member do
      post :invitation
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :board, class_name: 'Board'
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @boards = current_user.board
  end

  def destroy
    if current_user.present?
      @boards = current_user.board
      @boards.each do |board|
        @group = Group.find_by(board_id: board.id, user_id: current_user.id)
      end
    end
    @group.destroy
    redirect_to boards_path
  end

  def invitation
    @user = User.find(params[:id])
    @boards = @user.board
    @group = Group.new(board_params)
    @group.user_id = @user.id
    if @group.save
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private

  def board_params
    params.permit(:board_id)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/index.html.erb
<div class=" items-center px-5 lg:px-20">
  <div class="flex flex-col w-full max-w-md p-5 mx-auto my-3 transition duration-500 ease-in-out transform bg-white rounded-lg md:mt-0">
    <div class="text-center">
        <h1 class="mt-6 text-3xl font-extrabold text-neutral-600">ユーザー一覧</h1>

        <div class="relative mt-4 mb-2">
          <div class="absolute inset-0 flex items-center">
            <div class="w-full border-t border-gray-300"></div>
          </div>
          <div class="relative flex justify-center text-sm">
              <span class="px-2 text-neutral-600 bg-white"></span>
          </div>
        </div>

        <% @users.each do |user| %>
          <p><%= link_to user.name, group_path(user.id), method: :get, class: "block text-lg font-medium text-neutral-600 p-3" %></p><hr>
        <% end %>
      </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class=" items-center px-5 lg:px-20">
  <div class="flex flex-col w-full max-w-md p-5 mx-auto my-3 transition duration-500 ease-in-out transform bg-white rounded-lg md:mt-0">
    <div class="text-center">
      <h1 class="mt-6 text-3xl font-extrabold text-neutral-600">ユーザー詳細</h1>
      <span class="mt-6 text-xl font-semibold text-neutral-600"><%= @user.name %></span>

      <div class="relative mt-4 mb-2">
        <div class="absolute inset-0 flex items-center">
          <div class="w-full border-t border-gray-300 mb-6"></div>
        </div>
        <div class="relative flex justify-center text-sm">
        </div>
      </div>

      <%= form_with model: @board, url: invitation_group_path(@user.id), method: :post, local: true do |f| %>
        <%= f.collection_select(:board_id, @boards, :id, :title, prompt: "選択してください。") %>
        <%= f.submit "招待", class: "flex items-center justify-center w-full px-10 py-4 mt-6 text-base font-medium text-center text-white transition duration-500 ease-in-out transform bg-blue-600 rounded-xl hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
      <% end %>
    </div>
  </div>
</div>