config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  devise_scope :user do
    put "confirmation", to: "users/confirmations#show", as: :back_confirmation
  end

  root to: "boards#index"
  resources :users
  resources :boards do
    get "join" => "board#join"
    resources :favorites, only: [:create, :destroy]
    resources :lists do
      resources :cards
    end
  end
  resources :groups do
    member do
      post :invitation
    end
  end
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :group, class_name: "Group", foreign_key: "board_id"
  has_many :users, through: :group
  has_many :favorites
  has_many :lists
  validates :title, presence: true
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def index
    if current_user.present?
      @boards = current_user.board
      @boards.each do |board|
        @group = Group.where(board_id: board.id, user_id: current_user.id)
      end
    end
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      Group.create(user_id: current_user.id, board_id: @board.id)
      redirect_to root_path
    else
      render action: :new
    end
  end

  def show
    @board = Board.find(params[:id])
    @favorite = Favorite.find_by(user_id: current_user.id, board_id: @board.id)
    @groups = Group.where(board_id: @board.id).count
    @lists = List.where(board_id: params[:id])
    @lists.each do |list|
      @cards = Card.where(list_id: list.id)
    end
  end

  def edit
    @board = Board.find(params[:id])
    @groups = Group.where(board_id: @board.id)
    @users = @board.users
  end

  def update
    @board = Board.find(params[:id])
    @board.title = params[:board][:title]
    if @board.save
      redirect_to board_path(params[:id])
    else
      render action: :edit
    end
  end

  def destroy
    @board = Board.find(params[:id])
    if @board.destroy
      redirect_to boards_path
    else
      render action: :edit
    end
  end

  def join
    @board = Board.find(params[:group_id])
    @board.users << current_user
    redirect_to root_path
  end

  private

    def board_params
      params.require(:board).permit(:title)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/edit.html.erb
<div class="items-center px-5 lg:px-20">
  <div class="flex flex-col w-full max-w-md p-5 mx-auto my-3 transition duration-500 ease-in-out transform bg-white rounded-lg md:mt-0">
    <div class="text-center">
      <h1 class="mt-6 text-3xl font-extrabold text-neutral-600">ボード編集</h1>

      <div class="relative mt-4 mb-2">
        <div class="absolute inset-0 flex items-center">
          <div class="w-full border-t border-gray-300"></div>
        </div>
        <div class="relative flex justify-center text-sm">
            <span class="px-2 text-neutral-600 bg-white"></span>
        </div>
      </div>

      <%= form_with model: @board, url: board_path(@board.id), method: :patch, local: true do |f| %>
        <%= f.label :title, "ボード名編集" %>
        <%= f.text_field :title, class: "block w-full px-5 py-3 text-base text-neutral-600 placeholder-gray-300 transition duration-500 ease-in-out transform border border-transparent rounded-lg bg-gray-50 focus:outline-none focus:border-transparent focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-300 mt-4 mb-7" %>
        <%= f.submit "変更", class: "flex items-center justify-center w-full px-10 py-4 text-base font-medium text-white transition duration-500 ease-in-out transform bg-blue-600 rounded-xl hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
      <% end %>
      <%= button_to "削除", board_path(@board.id), { method: :delete, class: "flex items-center justify-center w-full px-10 py-4 text-base font-medium text-white transition duration-500 ease-in-out transform bg-blue-600 rounded-xl hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 mt-7", form: { data: { confirm: "本当に削除しますか？" } } } %>

      <div class="relative mt-4 mb-2">
        <div class="absolute inset-0 flex items-center">
          <div class="w-full border-t border-gray-300"></div>
        </div>
        <div class="relative flex justify-center text-sm">
            <span class="px-2 text-neutral-600 bg-white"></span>
        </div>
      </div>

      <h1 class="mt-6 text-3xl font-extrabold text-neutral-600 mb-2">グループメンバー</h1>
      <% @users.each do |user| %>
        <div class="flex items-center justify-center">
          <div class="text-meddium py-2 ml-4 mr-10 font-medium">
            <%= user.name %>
            <%# 最新のメンバーしか表示されない %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/boards/index.html.erb
<div class=" items-center px-5 lg:px-20">
  <div class="max-w-md p-5 mx-auto my-3 transition duration-500 ease-in-out transform bg-white rounded-lg md:mt-0">
    <div class="text-center">
      <% if current_user.present? %>
        <% if @boards.present? %>
          <h1 class="mt-6 text-3xl font-extrabold text-neutral-600"><%= current_user.name%>のボード一覧</h1>

            <div class="relative mt-4 mb-1">
              <div class="absolute inset-0 flex items-center">
                <div class="w-full border-t border-gray-300"></div>
              </div>
              <div class="relative flex justify-center text-sm">
                  <span class="px-2 text-neutral-600 bg-white"></span>
              </div>
            </div>

          <% @boards.each do |board| %>
            <div class="mt-2">
              <%= link_to board.title, board_path(board.id), class: "text-lg font-medium text-neutral-600 p-3" %>
              <%= button_to "退会", group_path(@group.ids), { method: :delete, class: "px-8 py-2 mt-3 mb-4 text-base font-medium text-white transition duration-500 ease-in-out transform bg-blue-600 rounded-xl hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" } %><hr>
            </div>
          <% end %>
        <% else %>
          <h1>新規ボードを作成してください。</h1>
          <%= link_to "ボードを作成する", new_board_path, class: "text-blue-700" %>
        <% end %>
      <% else %>
        <h1><%= link_to "ログイン", new_user_session_path, class: "text-blue-700" %>してください。初めてご利用される方は、<%= link_to "新規登録", new_user_registration_path, class: "text-blue-700" %>してください。</h1>
      <% end %>
    </div>
  </div>
</div>

app/views/boards/new.html.erb
<div class=" items-center px-5 lg:px-20">
  <div class="flex flex-col w-full max-w-md p-5 mx-auto my-3 transition duration-500 ease-in-out transform bg-white rounded-lg md:mt-0">
    <div class="text-center">
        <h1 class="mt-6 text-3xl font-extrabold text-neutral-600">ボード新規作成</h1>

        <div class="relative mt-4 mb-2">
          <div class="absolute inset-0 flex items-center">
            <div class="w-full border-t border-gray-300"></div>
          </div>
          <div class="relative flex justify-center text-sm">
              <span class="px-2 text-neutral-600 bg-white"></span>
          </div>
        </div>

        <%= form_with model: @board, local: true do |f| %>
          <%= f.text_field :title, placeholder: "ボード名", class: "block w-full px-5 py-3 text-base text-neutral-600 placeholder-gray-300 transition duration-500 ease-in-out transform border border-transparent rounded-lg bg-gray-50 focus:outline-none focus:border-transparent focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-300 my-7" %>
          <%= f.submit "作成", class: "flex items-center justify-center w-full px-10 py-4 text-base font-medium text-center text-white transition duration-500 ease-in-out transform bg-blue-600 rounded-xl hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
        <% end %>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<div class=" items-center px-5 lg:px-20">
  <div class="flex flex-col w-full max-w-md p-5 mx-auto my-3 transition duration-500 ease-in-out transform bg-white rounded-lg md:mt-0">
    <div class="text-center">
      <h1 class="mt-6 text-3xl font-extrabold text-neutral-600">
        <%= link_to @board.title, edit_board_path %>
      </h1>

      <% if Favorite.find_by(user_id: current_user.id, board_id: params[:id]) %>
        <%= button_to board_favorite_path(@board.id, @favorite.id), method: :delete do %>
          <div class="p-2 bg-stone-400 rounded-xl m-1">
            <i class="fa fa-solid fa-star" style="color: yellow;"></i>
          </div>
        <% end %>
      <% else %>
        <%= button_to board_favorites_path(@board.id), method: :post do %>
          <div class="p-2 bg-stone-400 rounded-xl m-1">
            <i class="fa fa-regular fa-star"></i>
          </div>
        <% end %>
      <% end %>

      <%= "メンバー：#{ @groups }人" %>
      <div class="relative mt-4 mb-2">
        <div class="absolute inset-0 flex items-center">
          <div class="w-full border-t border-gray-300"></div>
        </div>
        <div class="relative flex justify-center text-sm">
            <span class="px-2 text-neutral-600 bg-white"></span>
        </div>
      </div>
    </div>
  </div>
</div>

  <% if @lists.present? %>
  <div class="flex">
    <% @lists.each do |list| %>
    <div class="bg-purple-300 mx-10 px-10 pb-3 text-center">
      <div class="">
        <%= link_to list.content, edit_board_list_path(@board.id, list.id), class: "block text-lg text-neutral-600 pt-3 font-semibold" %>
      </div>
      <% list.cards.each do |card| %>
        <div class="my-4 bg-green-200">
          <%= link_to card.task, edit_board_list_card_path(@board.id, list.id, card.id) %>
        </div>
      <% end %>
      <%= link_to "新規カード作成", new_board_list_card_path(@board.id, list.id), class: "block" %>
    </div>
    <% end %>
    <%= link_to "新規リスト作成", new_board_list_path(@board.id), class: "text-right text-base mt-3" %>
  <% else %>
    <h1>リストを作成してください。</h1>
    <%= link_to "新規リスト作成", new_board_list_path(@board.id), class: "text-right text-base mt-3" %>
  <% end %>
  </div>