config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  devise_scope :user do
    put "confirmation", to: "users/confirmations#show", as: :back_confirmation
  end

  root to: "boards#index"
  resources :users
  resources :boards do
    get "join" => "board#join"
    resources :favorites, only: [:create, :destroy]
    resources :lists do
      resources :cards
    end
  end
  resources :groups do
    member do
      post :invitation
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list
  validates :task, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!

  def new
    @card = Card.new
    @board = Board.find(params[:board_id])
    @list = List.find(params[:list_id])
  end

  def create
    @board = Board.find(params[:board_id])
    @list = List.find(params[:list_id])
    @card = Card.new(card_params)
    if @card.save!
      redirect_to board_path(@board.id)
    else
      render action: :new
    end
  end

  def edit
    @board = Board.find(params[:board_id])
    @list = List.find(params[:list_id])
    @lists = List.where(board_id: @board.id)
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])
    @card.task = params[:card][:task]
    @card.list_id = params[:card][:list_id]
    if @card.save
      redirect_to board_path(params[:board_id])
    else
      render action: :edit
    end
  end

  def destroy
    # @board = Board.find(params[:board_id])
    # @list = List.find(params[:list_id])
    @card = Card.find(params[:id])
    if @card.destroy
      redirect_to board_path(params[:board_id])
    else
      render action: :edit
    end
  end

  private

  def card_params
    params.require(:card).permit(:task, :content, :list_id).merge(list_id: @list.id)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/edit.html.erb
<div class=" items-center px-5 lg:px-20">
  <div class="flex flex-col w-full max-w-md p-5 mx-auto my-3 transition duration-500 ease-in-out transform bg-white rounded-lg md:mt-0">
    <div class="text-center">
      <h1 class="mt-6 text-3xl font-extrabold text-neutral-600">カード編集</h1>

      <div class="relative mt-4 mb-2">
        <div class="absolute inset-0 flex items-center">
          <div class="w-full border-t border-gray-300"></div>
        </div>
        <div class="relative flex justify-center text-sm">
            <span class="px-2 text-neutral-600 bg-white"></span>
        </div>
      </div>

      <%= form_with model: @card, url: board_list_card_path(@board.id, @list.id, @card.id), method: :patch, local: true do |f| %>
        <%= f.label :content, "カードを移動", class: "block text-lg font-medium text-neutral-600 p-3" %>
        <%= f.collection_select(:list_id, @lists, :id, :content, prompt: "リストの変更") %>

        <div class="relative mt-4 mb-2">
        <div class="absolute inset-0 flex items-center">
          <div class="w-full border-t border-gray-300"></div>
        </div>
        <div class="relative flex justify-center text-sm">
            <span class="px-2 text-neutral-600 bg-white"></span>
        </div>
      </div>

        <%= f.label :task, "カード名編集", class: "block mt-7" %>
        <%= f.text_field :task, class: "block w-full px-5 py-3 text-base text-neutral-600 placeholder-gray-300 transition duration-500 ease-in-out transform border border-transparent rounded-lg bg-gray-50 focus:outline-none focus:border-transparent focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-300 mt-4 mb-7" %>
        <%= f.submit "変更", class: "flex items-center justify-center w-full px-10 py-4 text-base font-medium text-center text-white transition duration-500 ease-in-out transform bg-blue-600 rounded-xl hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
      <% end %>

      <%= button_to "削除", board_list_card_path(@board.id, @list.id, @card.id), { method: :delete, class: "flex items-center justify-center w-full px-10 py-4 text-base font-medium text-center text-white transition duration-500 ease-in-out transform bg-blue-600 rounded-xl hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 mt-7", form: { data: { confirm: "本当に削除しますか？" } } } %>
    </div>
  </div>
</div>

app/views/cards/new.html.erb
<div class=" items-center px-5 lg:px-20">
  <div class="flex flex-col w-full max-w-md p-5 mx-auto my-3 transition duration-500 ease-in-out transform bg-white rounded-lg md:mt-0">
    <div class="text-center">
        <h1 class="mt-6 text-3xl font-extrabold text-neutral-600">カード新規作成</h1>

        <div class="relative mt-4 mb-2">
          <div class="absolute inset-0 flex items-center">
            <div class="w-full border-t border-gray-300"></div>
          </div>
          <div class="relative flex justify-center text-sm">
              <span class="px-2 text-neutral-600 bg-white"></span>
          </div>
        </div>

        <%= form_with model: @card, url: board_list_cards_path(@board.id, @list.id), method: :post, local: true do |f| %>
          <%= f.text_field :task, placeholder: "カード名", class: "block w-full px-5 py-3 text-base text-neutral-600 placeholder-gray-300 transition duration-500 ease-in-out transform border border-transparent rounded-lg bg-gray-50 focus:outline-none focus:border-transparent focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-300 my-7" %>
          <%= f.submit "作成", class: "flex items-center justify-center w-full px-10 py-4 text-base font-medium text-center text-white transition duration-500 ease-in-out transform bg-blue-600 rounded-xl hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
        <% end %>
    </div>
  </div>
</div>